AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
Style/FileName:
  Exclude:
    # usability - module name should match the gem name
    - 'lib/rake-terraform.rb'
Style/EndOfLine:
  EnforcedStyle: lf
Metrics/AbcSize:
  Exclude:
    # TODO - fix this
    - 'lib/rake-terraform/plan_task/task.rb'
Metrics/MethodLength:
  Max: 12
Metrics/ModuleLength:
  Exclude:
    - 'spec/unit/*_spec.rb'
Metrics/CyclomaticComplexity:
  Exclude:
      # TODO: fix tf_plan method to support splat arguments and break
      # down into one or more command constructor methods
      - 'lib/rake-terraform/terraformcmd.rb'
Metrics/PerceivedComplexity:
  Exclude:
      - 'lib/rake-terraform/terraformcmd.rb'
